change_readme.md
kg-ogura1008/chat-space pull request #1
Opened 2018-03-15 11:06 UTC by kg-ogura1008

2018-03-15 11:24 UTC, kohei-isoda reviewed
・外部キー（foreign key）制約があらゆるテーブルのカラムに付いています。こちらもう一度それぞれのカラムに対して必要か不必要か考えてみてください。
・usersテーブルのmember_id, message_idは不要です。ここで管理するものではありません。
・usersテーブルのnameは検索する機能をのちに実装しますので検索を高速化するためにindexをつけましょう！
・membersテーブルのuser_idが2つあります。どちらかを消しましょう。（idなのにtypeがstringなのは不適切なのでintegerの方を残すといいと思います）
・groupsテーブルでもmember_idとmessage_idを管理する必要はありませんので消しましょう。
・中間テーブル（member）のアソシエーションがないので追加しましょう！
・messagesテーブルにimageを管理するカラムがありませんので追加しましょう！

2018-03-15 11:53 UTC, kohei-isoda reviewed
・ foreign keyをつけないのであればわざわざfalseと書かないで消してしまって構いません！
・ 中間テーブルのアソシエーションがありませんので記述お願いいたします！参考リンクを下に貼っておきます！
https://qiita.com/Kohei_Kishimoto0214/items/cb9a3d3da57708fb52c9
・ messagesテーブルにあるmessageと言うカラム名は混同しやすいのでもしこだわりがなければ変更をオススメします！
・null false制約も全てのカラムにつける必要があるのか考えましょう！

2018-03-15 12:15 UTC, kohei-isoda requested changes

2018-03-15 12:15 UTC, kohei-isoda commented on README.md
> -- has_many :members
消してしまっていますがこちら必要となります！

2018-03-15 12:15 UTC, kohei-isoda commented on README.md
> -- has_many :menmbers
消してしまっていますがこちら必要となります！（スペルミスも修正願います）

2018-03-16 03:47 UTC, MrUrakou commented on README.md
> +|post    |text      |                              |
postよりもtextとかbodyの方がbetterな方が良いと思います。
postだと範囲が大きい気がします。

2018-03-16 04:01 UTC, kg-ogura1008 commented on README.md
> +|post    |text      |                              |
ありがとうございます！
textに変更してマージいたします。

2018-03-16 04:02 UTC, merged